[package]
name = "evaera/cmdr-lang"
version = "0.0.0"
author = "evaera"
content_root = "src"
license = "MIT"

[dependencies]
t = { git = "https://github.com/Roblox/t" }
TestEZ = { git = "https://github.com/Roblox/testez" }